Add RepoType to WatchProjectResource
xero-oss/go-xray pull request #6
Opened 2021-03-23 15:45 UTC by jasonwbarnett

The `repo_type` is included in xray watch responses and is required when adding remote repositories.

This is a required change to fix https://github.com/jfrog/terraform-provider-artifactory/issues/56

2021-03-23 15:49 UTC, jasonwbarnett commented
@KierranM and/or @AlexanderRMcNeill I'm proactively reaching out to you since I can see this project hasn't been updated in a couple of years. Is this project still being maintained or should I fork this project?

2021-03-24 16:47 UTC, jkumar19 commented
@jasonwbarnett - Thanks for providing repo_type parameter. When we are expecting this to be merged.

2021-03-24 18:01 UTC, chb0github requested changes
I don't see an updated test.

2021-03-24 19:05 UTC, jasonwbarnett commented
@chb0github I didn't see any relevant tests. In other words, it doesn't look like this is being tested at all.

2021-03-26 10:37 UTC, jkumar19 commented
> @chb0github I didn't see any relevant tests. In other words, it doesn't look like this is being tested at all. Given that this is an addition, it didn't seem necessary to add tests for something that wasn't being tested in the first place. I can't see how adding a field would have unintended consequences, but I don't know.

@jasonwbarnett @chb0github - Any update please?

2021-03-26 13:50 UTC, chb0github commented
I will get to you this morning

2021-03-26 15:36 UTC, chb0github commented
Wait a minute!!!! I had a total brain fart here. I don't know why I didn't see this earlier (and it explains my internal confusion) - this is not any code I own - it's a dependency we use. It's not on me to decide and even if I could, I can't commit anything. I can't help you

2021-03-26 16:12 UTC, jasonwbarnett commented
@chb0github do you think you should fork this code base since it looks like it's abandoned? That way we can modify the dependency in ways that makes sense for the other project.

2021-03-26 18:06 UTC, chb0github commented
Jfrog's official position is that we are only going to support our go client moving forward. With that in mind, if you fork this code, you will need to fork the provider too - as well as build and manage it. Not a big lift, frankly, but we can't support it.

2021-04-08 18:17 UTC, chb0github commented
Ok, now I get this - It's now up to me, but if they merge in, we can pull in the changes.

2021-04-08 18:23 UTC, chb0github commented
Did you notice that none of the **2** contributors has said a word? I can't help you without forking this code. At this point @jasonwbarnett I would consider this repo abandoned. If you want to contribute to the jfrog code base We can work really closely to do that - my job, my _soul purpose_ is community partner integration. PM on gitter. Let's work something out

2021-04-13 00:44 UTC, chb0github commented
So, you've already forked the repo - how about you keep your change and merge it into the master branch of your fork. 

Then, you update the `go.mod` in the provider to simply use your repo. Dead simple!

2021-04-13 17:08 UTC, jasonwbarnett commented
@chb0github updated the master branch as you suggested! https://github.com/jasonwbarnett/go-xray

2021-04-27 14:14 UTC, jasonwbarnett commented
Closing this out because the project is abandoned. I forked the project to continue the work.

2021-04-27 14:14 UTC, closed without merging